# Beispiel für Streamlit Cloud Secrets
# Diese Datei ist nur ein Beispiel. In Streamlit Cloud muss man diese Konfiguration 
# in der Web-Oberfläche unter "Manage App" > "Secrets" einfügen.

# OpenAI API Key - WICHTIG: Der Schlüssel muss auf dieser Ebene direkt definiert werden
openai_api_key = "IHRE_ECHTE_API_KEY_HIER_EINFÜGEN"

# Allgemeine Einstellungen
[general]
default_template = "Klassisch"
show_extracted_text = false 