# Template for Streamlit Secrets
# Rename this file to secrets.toml and add your actual API key

# OpenAI API Key
openai_api_key = "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"

# Add other secrets here if needed

[general]
# Hier können weitere Konfigurationseinstellungen hinzugefügt werden
default_template = "Klassisch"
show_extracted_text = false 
